# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :increment_version_build_numbers do
    increment_build_number_in_xcodeproj(xcodeproj: "Dozy.xcodeproj")
    increment_version_number_in_xcodeproj(bump_type: "patch", xcodeproj: "Dozy.xcodeproj")
  end
end
