name: Audits

on:
  schedule:
    - cron: 0 13 * * 1

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Package Audit
        run: yarn audit --groups dependencies --level high
