name: Build iOS

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - master
#     paths-ignore:
#       - README.md
#       - .eslintrc.json
#       - .eslintignore
#       - .gitignore
#       - .prettierrc.json

jobs:
  build:
    name: Production Build (iOS Testflight and Android Apps using EAS build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: iOS Bundle Install
        run: gem install bundler && bundle install
        working-directory: ./ios
      - name: Bumping version and iOS build number in app.json and project.pbxproj
        run: bundle exec fastlane increment_version_build_numbers
        working-directory: ./ios
      - name: Update Release Channel in Expo.plist
        run: bundle exec fastlane update_release_channel_prod
        working-directory: ./ios
      - name: Android Bundle Install
        run: bundle install
        working-directory: ./android
      - name: Bumping Android version code in app.json and version name & code in app/build.gradle
        run: bundle exec fastlane increment_version_build_numbers
        working-directory: ./android
      - name: Update Release Channel in AndroidManifest.xml
        run: bundle exec fastlane update_release_channel_prod
        working-directory: ./android
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - name: Commit iOS and Android Version and Gemfile Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "['ios/', 'android/', app.json]"
          default_author: github_actions
          message: 'bumped js, ios, android version and build numbers, set the production channel'
      - run: eas build --platform all --profile release --non-interactive
