name: Build iOS

on:
  push:
    branches:
      - develop
    paths-ignore:
      - README.md
      - .eslintrc.json
      - .eslintignore
      - .gitignore
      - .prettierrc.json
  pull_request:
    branches:
      - develop
      - feature/CI
    paths-ignore:
      - README.md
      - .eslintrc.json
      - .eslintignore
      - .gitignore
      - .prettierrc.json

jobs:
  build:
    name: Build the iOS and Android Apps using EAS build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: bundle install
        working-directory: ./ios
      - run: bundle exec fastlane increment_version_build_numbers
        working-directory: ./ios
      - run: bundle exec fastlane increment_version_build_numbers
        working-directory: ./android
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Prepare iOS Credentials
        run: echo ${{ secrets.CREDENTIALS_JSON_BASE64 }} | base64 -d > credentials.json
      - run: mkdir ios/certs
      - name: Create iOS Distribution Certificate
        run: echo ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }} | base64 -d > ios/certs/distribution_certificate.p12
      - name: Create iOS Ad-Hoc Provisioning Profile
        run: echo ${{ secrets.ADHOC_PROVISION_BASE64 }} | base64 -d > ios/certs/ad_hoc_provision.mobileprovision
      - run: yarn install
      - run: eas build --platform all --profile alpha --non-interactive
      - name: Commit iOS Version and Gemfile Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "['ios/', 'android/', app.json]"
          default_author: github_actions
          message: 'bumped js, ios, android version and build numbers'
