name: Build iOS

on:
  push:
    branches:
      - develop
    paths-ignore:
      - README.md
      - .eslintrc.json
      - .eslintignore
      - .gitignore
      - .prettierrc.json
  # pull_request:
  #   branches:
  #     - develop
  #     - feature/CI
  #   paths-ignore:
  #     - README.md
  #     - .eslintrc.json
  #     - .eslintignore
  #     - .gitignore
  #     - .prettierrc.json

jobs:
  build:
    name: Alpha Build (iOS Ad-hoc and Android Apps using EAS build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: iOS Bundle Install
        run: gem install bundler && bundle install
        working-directory: ./ios
      - name: Bumping version and iOS build number in app.json and project.pbxproj
        run: bundle exec fastlane increment_version_build_numbers
        working-directory: ./ios
      - name: Update Release Channel in Expo.plist
        run: bundle exec fastlane update_release_channel
        working-directory: ./ios
      - name: Android Bundle Install
        run: bundle install
        working-directory: ./android
      - name: Bumping Android version code in app.json and version name & code in app/build.gradle
        run: bundle exec fastlane increment_version_build_numbers
        working-directory: ./android
      - name: Update Release Channel in AndroidManifest.xml
        run: bundle exec fastlane update_release_channel
        working-directory: ./android
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          # expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      # - name: Get Release Channel
      #   id: release_channel
      #   uses: notiz-dev/github-action-json-property@release
      #   with:
      #     path: 'eas.json'
      #     prop_path: 'build.alpha.releaseChannel'
      # - name: Release Channel
      #   run: echo ${{ steps.release_channel.outputs.prop }}
      # - run: expo publish --release-channel ${{ steps.release_channel.outputs.prop }}
      - name: Commit iOS and Android Version and Gemfile Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "['ios/', 'android/', app.json]"
          default_author: github_actions
          message: 'bumped js, ios, android version and build numbers'
      - name: Prepare iOS Credentials
        run: echo ${{ secrets.CREDENTIALS_JSON_BASE64 }} | base64 -d > credentials.json
      - run: mkdir ios/certs
      - name: Create iOS Distribution Certificate
        run: echo ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }} | base64 -d > ios/certs/distribution_certificate.p12
      - name: Create iOS Ad-Hoc Provisioning Profile
        run: echo ${{ secrets.ADHOC_PROVISION_BASE64 }} | base64 -d > ios/certs/ad_hoc_provision.mobileprovision
      - run: eas build --platform all --profile alpha --non-interactive
